#!/bin/bash

:<<!
####预设置####
查看是否安装mailx，没有请先安装
which mailx

vim /etc/mail.rc 最后添加如下
set from=qishanqing@dafy.com smtp=smtp.qiye.163.com smtp-auth-user=qishanqing@dafy.com smtp-auth-password=qsq_372233 smtp-auth=login

##############
!
set -e

cm_mails=qishanqing@dafy.com

if test "$SMARTCM_EXTRA_MAIL"; then
	cm_mails="$cm_mails $SMARTCM_EXTRA_MAIL"
fi


## start code-generator "^\\s *#\\s *"
# generate-getopts  iinput
## end code-generator
## start generated code
input=false
OPTIND=1
while getopts 'i' opt; do
	case "$opt" in
		i)    input=true;;
		*)    echo Usage Error; exit 2;;
	esac
done
shift $(($OPTIND - 1))

## end generated code

if test "$input" = true; then
	cat
else
	echo
fi | /bin/mailx -S from=qishanqing@dafy.com  -S smtp=localhost:25 -s "$*" $cm_mails ||  true


