deeplearning:
    log:
        end: 0
        debug: 0
        time: 0
        test: 1
        status: 1
    display: 0
    # 动静态判定半径
    radius: 0.5
    # 动静态判定帧率
    diagconditon: 10
    # 危险区域判定距离
    distance: 3.0
    # 危险区域判定角度
    angle: 30
    structure:
        lidarDirection: true
        # 导航激光 水平夹角/deg
        lidarAngle: 1.5
        # 导航激光
        pose2Machine: [0.15863, 0, 0.1455]
        # 双目镜头 - 导航激光
        leftcamera2lidar: [0.04973, 0.06, 0.136]
        rightcamera2lidar: [0.04973, -0.06, 0.136]
        # 相机高度 双目 + 轮高/2
        cameraHeight: 0.366
        cameraAngle: 0
    threshold: 0.5
    timeMargin: 70
    saveData:
        Path: ""
        checkObject: false
