# src file
if(USE_GPU)
    message(STATUS "[device] use gpu")
    add_definitions(-DUSE_GPU)
    list(APPEND SRC_DIR ${ROOT_DIR}/src/module/gpu)
elseif(NPU STREQUAL "aml")
    message(STATUS "[device] use amlogic npu")
    add_definitions(-DUSE_NPU_AML)
    list(APPEND SRC_DIR ${ROOT_DIR}/src/module/npu_aml ${ROOT_DIR}/src/module/npu_aml/vnn)
elseif(NPU STREQUAL "rk")
    message(STATUS "[device] use rockchip npu")
    add_definitions(-DUSE_NPU_RK)
    list(APPEND SRC_DIR ${ROOT_DIR}/src/module/npu_rk)
else()
    message(FATAL_ERROR "please set the device USE_GPU=ON or NPU=aml|rk")
endif()

# lib
set(NPU_LIBRARIES -lOpenVX -lOpenVXU -lArchModelSw -lCLC -lGAL -lNNArchPerf -lVSC -lovxlib)

if (NPU STREQUAL "aml")
    set(AML_LIB /usr/share/npu/sdk/include/)
    message(STATUS "aml npu include: " ${AML_LIB})
    include_directories(${AML_LIB})
    set(CNN_LIBRARY ${NPU_LIBRARIES})
elseif(NPU STREQUAL "rk")
    message(STATUS "rockchip npu lib: ")
    set(CNN_LIBRARY -lrknnrt)
elseif(USE_GPU)
    message(STATUS "gpu include: " ${MNN_DIR}/include)
    include_directories(${MNN_DIR}/include)
    set(CNN_LIBRARY ${MNN_DIR}/lib/libMNN.so)
endif ()