%YAML:1.0
---
############# EVT1 ########################
## O系到tof系
#t_ot: [0.493388,0.0,0.520128] #t系原点在o系中的位置
#Ry_ot: 110  #110.5 绕y轴顺时针转110度
#Rz_ot: 0  #-1.3;  //绕z轴逆时针转1.3度
#
## O系到s系
#t_os: [0.455488,0.0,0.331228] #s系原点在o系中的位置
#Rz_os: 90  #先绕z轴顺时针转90度
#Rx_os: 170 #再绕x轴顺时针转170度
#
## O系到地面系
#t_og: [0,0,-0.085] #g系原点在o系中的位置

############# EVT2 ########################
# O系到tof系
#t_ot: [0.22067,0.00212,0.51423] #t系原点在o系中的位置
#Ry_ot: 126  #110.5  #绕y轴顺时针转110度
#Rz_ot: 180  #-1.3;  #绕z轴逆时针转1.3度
#
## O系到s系
#t_os: [0.1945,0.0,0.248] #s系原点在o系中的位置
#Rz_os: 90  #先绕z轴顺时针转90度
#Rx_os: 170 #再绕x轴顺时针转170度
#
## O系到地面系
#t_og: [0,0,-0.085] #g系原点在o系中的位置

############## 改装EVT2 ########################  暂时是指 N3
## O系到tof系
#t_ot: [0.1942,-0.0005,0.56152] #t系原点在o系中的位置
#Ry_ot: 128.5  #110.5  #绕y轴顺时针转110度
#Rz_ot: 0 #绕z轴逆时针转1.3度
#
## O系到s系
#t_os: [0.1945,0.0,0.248] #s系原点在o系中的位置
#Rz_os: 90  #先绕z轴顺时针转90度
#Rx_os: 170 #再绕x轴顺时针转170度
#
## O系到地面系
#t_og: [0,0,-0.085] #g系原点在o系中的位置

############## EVT3 ########################  暂时是指 N3
## O系到tof系
#t_ot: [0.19603,0.0,0.5871] #t系原点在o系中的位置
#Ry_ot: 128.5  #110.5  #绕y轴顺时针转110度
#Rz_ot: 0 #绕z轴逆时针转1.3度
#
## O系到s系
#t_os: [0.202,0.0,0.467] #s系原点在o系中的位置
#Rz_os: -90 #90  #先绕z轴顺时针转90度
#Rx_os: -90 #180 #再绕x轴顺时针转170度
#
## O系到地面系
#t_og: [0,0,-0.085] #g系原点在o系中的位置

################ ICE-EVT3 ############################
# # O系到tof系
# t_ot: [0.19987,0.0,0.57328] #t系原点在o系中的位置
# Ry_ot: 127  #110.5  #绕y轴顺时针转110度
# Rz_ot: 0 #绕z轴逆时针转1.3度

# # O系到s系
# t_os: [0.2131,0.0,0.4865] #s系原点在o系中的位置
# Rz_os: -90 #90  #先绕z轴顺时针转90度
# Rx_os: -90 #180 #再绕x轴顺时针转170度

# # O系到地面系
# t_og: [0,0,-0.0635] #g系原点在o系中的位置

################ Rubby ############################
# O系到tof系
t_ot: [0.0,0.0,0.0] #t系原点在o系中的位置
Ry_ot: 0  #110.5  #绕y轴顺时针转110度
Rz_ot: 0 #绕z轴逆时针转1.3度

# O系到s系
t_os: [0.15418,0.0,0.017] #s系原点在o系中的位置
Rz_os: -90 #90  #先绕z轴顺时针转90度
Rx_os: -80 #180 #再绕x轴顺时针转170度


# O系到地面系
t_og: [0,0,-0.03] #g系原点在o系中的位置
