%YAML:1.0
---
run_dataset: 0 #bool
display_img: 0 #bool
display_laser: 0 #bool
output_camera_center: 0 #bool 1 for abby , 0 for i18R && i26R

simulator: 0 #bool

frequency_division: 2 #frequency division

# for calibration online
duration_one_echo_for_calibration_online: 1000 # ms, must more than 500ms
light_frequency_division: 1 # adjust light and output calib img frequency division

# recorder
recorde_file: "depth_data3" #string
record: 0 #bool
record_tof_data: 0 #bool
record_img_date: 0 #bool
record_laser_date: 0 #bool
record_without_any_computation: 0 #bool 注意，打开之后会没有亮度调节功能！！ record打开才生效，生效后不再进行任何算法计算
record_frequency_division: 1

# log
log_rank: [1,1,1,1,1,1] #int 0, 1, 2, 3  从左到右依次为 depth_impl，monitor，laser，tof，img, light

# init
sleep_in_init: 0 # seconds
sleep_in_tof_thread: 5 # sleep_in_tof_thread * 10 ms

# tof and stereo choice
use_multithread: 1 #bool
run_tof: 0 #bool
run_stereo: 1 #bool
run_laser_computation: 1 #bool

use_gpu: 0 #bool

# camera param
read_camera_param: 0 #bool
camera_param_file: "/home/icecola/temp/MoudleParam.yaml" #string

# roi
top_border: 165
bottom_border: 35
left_border: 5
right_border: 5

# laser distance limits
height_limit: [-1,-0.02,0.015,0.11] #0.05,0.07,0.09,0.11] #0.65,0.72]  # the height of ground is -0.125
max_distance_for_tof: 3.0 #与车体中心的距离
min_distance_for_tof: 0.3 #与车体中心的距离， 应至少大于原点与车体中心的位置偏移
max_distance_for_camera: 0.75 #与车体中心的距离
min_distance_for_camera: 0.2 #与车体中心的距离
default_error_before_calib: 0.005 #标定前默认的高度允许误差

# deviation
angle_pitch_deviation: 2.5 #float
angle_roll_deviation: 1.0 #float
z_deviation: 0.02 #float
distance_deviation_percent: 0.01 #float

# temp
compute_tof_blined_erae: 1 #bool
tof_blined_distance: 0.2 #float

#####################
# reserve
temp_bool: 0 #bool
temp_int: 5 #int
temp_float: 0.04 #float

###############################################################################
# for ros
enable_pub_laser: 1 #bool
enable_pub_camera_laser: 0 #bool
enable_pub_tof_depth: 0 #bool
enable_pub_stereo_depth: 0 #bool
enable_sub_tof: 0 #bool
enable_sub_img: 0 #bool
enable_sub_pose: 0 #bool
enable_pub_tf: 1 #bool
enable_sub_tof_is_PointCloud2: 0 #bool
enable_pub_3dmap: 0 #bool

sub_tof_topic: "/tof/front" # "/royale_camera_driver/point_cloud"   #/tof/front  /camera/depth/points
sub_img_topic: "/camera/image"
tof_link: "point_link" #"royale_camera_link" #"point_link"  #"royale_camera_optical_frame"  "base_footprint" #
camera_link: "camera_link"

updata_timestamp: 0 #bool
mapping_distance: 0.75 #float 距离相机
vanishing_distance: -1 #0.75 #float 距离相机
###############################################################################

calibrate_tof_mode: 0 #int 0-do not calib  1-calibrate till succeed  2-keep calibrating
calibrate_cam_mode: 0 #int 0-do not calib  1-calibrate till succeed  2-keep calibrating

###############################################
checkcalib: 1 #bool