#!/bin/bash

declare -A h5_author
declare -A h5_project
declare -A admin
declare -A mallStage_author
declare -A mallStage_project
declare -A DFLib_author
declare -A DFLib_project
declare -A Android_author
declare -A Android_project
declare -A Ios_author
declare -A Ios_project

admin[01]=qishanqing
admin[02]=builder

admin_project[01]="Tag/"

h5_author[01]=lihao
h5_author[02]=leiwanda
h5_author[03]=jiasaichao
h5_author[04]=liuxueqin
h5_author[05]=xupengyue
h5_author[06]=wanghongxiang

h5_project[01]="Mobile/CloudLoanH5Client/common"
h5_project[02]="Mobile/CloudLoanH5Client/config.json"
h5_project[03]="Mobile/CloudLoanH5Client/localcache.json"
h5_project[04]="Mobile/CloudLoanH5Client/staticGuidePage.htm"

mallStage_author[01]=wanghaitao
mallStage_author[02]=caoyanjie
mallStage_author[03]=wangxia
mallStage_author[04]=yiwangcheng
mallStage_author[05]=tianyanpin

mallStage_project[01]="Mobile/CloudLoanH5Client/mallStage"

DFLib_author[01]=lijinming
DFLib_author[02]=leiwanda

DFLib_project[01]="DFLib"

Android_author[01]=zhaojianxin
Android_author[02]=zhangfengzhou

Android_project[01]="MobileWallet/Android/ZiRu"

Ios_author[01]=zhaojianxin
Ios_author[02]=zhangliang

Ios_project[01]="MobileWallet/IOS/ZiRu"
