monitor_topic:
  rate: 1.0
  enable_report: false
  enable_watch: true
  topics:
    - [ "/encoder", 30, 0.8 ]
    - [ "/img_tx", 12, 0.8 ]
    - [ "/img_ir", 12, 0.8 ]
    - [ "/imu", 200, 0.8 ]
    - [ "/lightflow", 30, 0.8 ]
    - [ "/speed", 50, 0.8 ]
    - [ "/pose", 25, 0.8 ]
    - [ "/map", 1, 0.0 ]
    - [ "/senmatic_map", 1, 0.0 ]
    - [ "/motor_current", 1, 0.0 ]
    - [ "/pointcloud", 1, 0.0 ]