senmatic:
  - {classId: 1, name: SHOES, stype: 0, expansion: 0.275}
  - {classId: 2, name: BIN, stype: 0, expansion: 0.275}
  - {classId: 3, name: PEDESTAL, stype: 0, expansion: 0.275}
  - {classId: 4, name: WIRE, stype: 0, expansion: 0.275}
  - {classId: 5, name: SOCKET, stype: 0, expansion: 0.275}
  - {classId: 6, name: CAT, stype: 1, expansion: 1}
  - {classId: 7, name: DOG, stype: 1, expansion: 1}
  - {classId: 8, name: DESK_RECT, stype: 1, expansion: 1}
  - {classId: 9, name: DESK_CIRCLE, stype: 1, expansion: 1}