deeplearning:
    log:
        end: 0
        debug: 0
        time: 0
        test: 1
        status: 1
    display: 0
    # 动静态判定半径
    radius: 0.5
    # 动静态判定帧率
    diagconditon: 10
    # 危险区域判定距离
    distance: 3.0
    # 危险区域判定角度
    angle: 30
    detect:
        modelType: 3
        padding: true
    structure:
        lidarDirection: false
        lidarAngle: 2
        pose2Machine: [0.1433, 0, 0.1857]
        leftcamera2lidar: [0.0594, 0.062, 0]
        rightcamera2lidar: [0.0594, 0.062, 0]
    threshold: 0.5
    timeMargin: 70
    saveData:
        Path: ""
        checkObject: false
