EncoderL:
  Freq:
    Normal: 30
    Warn: 20
    Fault: 10
  Timeout: 100
  Restart: false
  WarnEnable: true
VelocityW:
  Freq:
    Normal: 50
    Warn: 40
    Fault: 30
  Timeout: 100
  Restart: false
  WarnEnable: true
Debug:
  Record: false
VelocityL:
  Timeout: 100
  Restart: false
  WarnEnable: true
  Freq:
    Warn: 40
    Fault: 30
    Normal: 50
EncoderR:
  Timeout: 100
  Restart: false
  WarnEnable: true
  Freq:
    Normal: 30
    Warn: 20
    Fault: 10
IMG:
  WarnEnable: true
  Freq:
    Warn: 22
    Fault: 17
    Normal: 25
  Timeout: 100
  Restart: false
Config:
  PrintDuty: 10
IMU:
  Timeout: 100
  Restart: false
  Freq:
    Normal: 200
    Fault: 50
    Warn: 100
  WarnEnable: true
WallL:
  Freq:
    Normal: 30
    Warn: 20
    Fault: 10
  Timeout: 100
  Restart: false
  WarnEnable: true
WallR:
  Freq:
    Normal: 30
    Warn: 20
    Fault: 10
  Timeout: 100
  Restart: false
  WarnEnable: true
DropL:
  Freq:
    Normal: 50
    Warn: 40
    Fault: 30
  Timeout: 100
  Restart: false
  WarnEnable: true
DropR:
  Freq:
    Normal: 50
    Warn: 40
    Fault: 30
  Timeout: 100
  Restart: false
  WarnEnable: true
Cliff1:
  Freq:
    Normal: 50
    Warn: 40
    Fault: 30
  Timeout: 100
  Restart: false
  WarnEnable: true
Cliff2:
  Freq:
    Normal: 50
    Warn: 40
    Fault: 30
  Timeout: 100
  Restart: false
  WarnEnable: true
Event:
  Freq:
    Normal: 50
    Warn: 40
    Fault: 30
  Timeout: 100
  Restart: false
  WarnEnable: true
SpdSend:
  Freq:
    Normal: 50
    Warn: 22
    Fault: 17
  Timeout: 100
  Restart: false
  WarnEnable: true
LightFlow:
  Freq:
    Normal: 30
    Warn: 20
    Fault: 10
  Timeout: 100
  Restart: false
  WarnEnable: true
GroundSig:
  Freq:
    Normal: 50
    Warn: 40
    Fault: 30
  Timeout: 100
  Restart: false
  WarnEnable: true
WorkMode:
  Freq:
    Normal: 50
    Warn: 40
    Fault: 30
  Timeout: 100
  Restart: false
  WarnEnable: true