AllInfo:
  DevType: RUBBY
  HWVer: RUBBY
  Product: INDEMIND
  EquipmentUse: INTG
  CurVer: V1.1.6.3
MainCala:
  RunMode: high-performance
  IP: 192.168.10.100
  MAC: None
  Usage: None
  DevNum: CHBNN0DALY
  AccessVerList: ALL
Imsee:
  LightBrightness: Auto
  CameraExposureMode: Auto
  CameraAcquisitionMode: TexureAndLight
  AccessVerList: V1.1,V1.2
  PictureResolution: 640*480
  TexureBrightness: Auto
  DevNum: CHBCC0DAXD
  FrameRate: 25
  DataFormat: YCrCb422
  IMU: 2G
  IMUFreq: 1000
  IMUFilter: ALL
  IMUTimeStampDelay: 40ms
  CameraTimeStampDelay: 40ms
  Record: false
  RecordImg: false
  FirmwareProtocolVersion: 2
  IMUv2: BMI055
McuData:
  CurVer: V1.1.6.3
  Record: false
  Device: /dev/ttyUSB0
  WorkMode: lidar
  HWVer: RUBBY
  EquipmentUse: INTG
  Baudrate: 1000000
  Product: INDEMIND
  DevType: RUBBY
KeyBoard:
  LineSpeed: 0.1
  InUse: false
  RotationSpeed: 1
MultiModule:
  Record: false
SensorControl:
  all: true
  mcudata: true
  monitor: true
  imsee: true
  multimodule: true
Priority:
  Imu: 10
  McuData: 5
  Img: 5
